services:
  - type: web
    name: omda-api
    runtime: node
    rootDir: server
    buildCommand: npm install && npx prisma generate
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        value: postgresql://neondb_owner:npg_aMlEL4SeKC1m@ep-fragrant-flower-ae8edjlb-pooler.c-2.us-east-2.aws.neon.tech/neondb?sslmode=require
      - key: JWT_SECRET
        generateValue: true
      - key: NODE_ENV
        value: production
